import { Themes } from './themer.types'

const themes: Themes = {
    'Default Theme': {
        '--text-navbar--alt': '#000000',
        '--br-secondary': '#7d7d7d',
        '--br-circuit-cur': '#ffffff',
        '--br-circuit': '#454545',
        '--cus-radio_label': '#656565',
        '--primary': '#454545',
        '--text-lite': '#ffffff',
        '--text-dark': '#000000',
        '--text-panel': '#ffffff',
        '--bg-navbar': '#454545',
        '--qp-br-tl': '#333333',
        '--qp-br-rd': '#535353',
        '--qp-box-shadow-1': '#3b3b3b',
        '--qp-box-shadow-2': '#4f4f4f',
        '--bg-circuit': '#dddddd',
        '--br-primary': '#ffffff',
        '--bg-primary-moz': '#454545e6',
        '--bg-primary-chr': '#454545b3',
        '--bg-tabs': '#8b8b8b',
        '--bg-icons': '#7d7d7d',
        '--bg-text': '#cacaca',
        '--bg-secondary': '#bbbbbb',
        '--canvas-stroke': '#eeeeee',
        '--canvas-fill': '#ffffff',
        '--context-text': '#ffffff',
        '--bg-toggle-btn-primary': '#42b983',
        '--primary-btn-hov': '#3ca877',
        '--btn-danger': '#dc5656',
        '--btn-danger-darken': '#b03662',
        '--disable': '#6c8b93',
        '--cus-btn-hov--bg': '#dddddd',
        '--cus-btn-hov-text': '#000000',
        '--node': '#008000',
        '--stroke': '#000000',
        '--fill': '#ffffff',
        '--hover-and-sel': 'rgba(255, 255, 32, 0.8)',
        '--wire-draw': '#000000',
        '--wire-cnt': '#008000',
        '--wire-pow': '#90ee90',
        '--wire-sel': '#0000ff',
        '--wire-lose': '#ff0000',
        '--mini-map': '#008000',
        '--mini-map-stroke': '#006400',
        '--input-text': '#008000',
        '--secondary-stroke': '#ff0000',
        '--text': '#000000',
        '--wire-norm': '#000000',
        '--node-norm': '#008000',
        '--splitter': '#000000',
        '--output-rect': '#0000ff',
        '--table-head-dark': '#3d3d3d',
    },
    'Night Sky': {
        '--text-navbar--alt': '#ffffff',
        '--br-secondary': '#665627',
        '--cus-radio_label': '#0f111a',
        '--primary': '#0f111a',
        '--text-lite': '#ffffff',
        '--text-dark': '#ffffff',
        '--text-panel': '#ffffff',
        '--bg-navbar': '#0f111a',
        '--br-circuit': '#0f111a',
        '--br-primary': '#665627',
        '--br-circuit-cur': '#cccccc',
        '--bg-circuit': '#bdc2ca',
        '--bg-primary-moz': '#0f111ae6',
        '--bg-primary-chr': '#0f111ab3',
        '--bg-tabs': '#727d8d',
        '--bg-icons': '#4d647a',
        '--bg-text': '#727d8d',
        '--bg-secondary': '#536c84',
        '--canvas-fill': '#1b2c33',
        '--canvas-stroke': '#6a7980',
        '--context-text': '#ffffff',
        '--bg-toggle-btn-primary': '#48a69d',
        '--primary-btn-hov': '#3f9189',
        '--btn-danger': '#c33c6c',
        '--btn-danger-darken': '#b03662',
        '--qp-br-tl': '#282d46',
        '--qp-br-rd': '#1d2132',
        '--qp-box-shadow-1': '#1d2132',
        '--qp-box-shadow-2': '#0a0b11',
        '--cus-btn-hov--bg': '#48a69d',
        '--cus-btn-hov-text': '#ffffff',
        '--node': '#285963',
        '--stroke': '#35aea9',
        '--fill': '#defffe',
        '--hover-and-sel': '#e3b924',
        '--wire-draw': '#77878c',
        '--wire-cnt': '#3b7f58',
        '--wire-pow': '#75ffb0',
        '--wire-sel': '#208cc9',
        '--wire-lose': '#bf0426',
        '--mini-map': '#3b7f58',
        '--mini-map-stroke': '#607f6e',
        '--input-text': '#3b7f58',
        '--output-rect': '#0487d9',
        '--secondary-stroke': '#bf0426',
        '--text': '#e9fbf8',
        '--wire-norm': '#277f7c',
        '--node-norm': '#ffc231',
        '--splitter': '#0284a8',
        '--disable': '#4f74b0',
        '--table-head-dark': '#000000',
    },
    'Lite-born Spring': {
        '--text-navbar--alt': '#000000',
        '--br-secondary': '#6b6b6b',
        '--cus-radio_label': '#6b6b6b',
        '--primary': '#eaeaeb',
        '--text-dark': '#6b6b6b',
        '--text-lite': '#ffffff',
        '--text-panel': '#6b6b6b',
        '--bg-navbar': '#6b6b6b',
        '--qp-br-tl': '#969696',
        '--qp-br-rd': '#545454',
        '--qp-box-shadow-1': '#747474',
        '--qp-box-shadow-2': '#5f5f5f',
        '--bg-tabs': '#a4a4a4',
        '--br-circuit-cur': '#42b983',
        '--bg-circuit': '#d7d7d7',
        '--br-circuit': '#42b983',
        '--br-primary': '#42b983',
        '--context-text-hov': '#6b6b6b',
        '--context-text': '#ffffff',
        '--bg-primary-moz': 'rgba(107, 107, 107, 0.904)',
        '--bg-primary-chr': 'rgba(107, 107, 107, 0.704)',
        '--bg-icons': '#dddddd',
        '--bg-text': '#dddddd',
        '--bg-secondary': '#6b6b6b',
        '--bg-toggle-btn-primary': '#42b983',
        '--primary-btn-hov': '#66c89c',
        '--btn-danger': '#bf2424',
        '--btn-danger-darken': '#bf414c',
        '--cus-btn-hov--bg': '#42b983',
        '--cus-btn-hov-text': '#ffffff',
        '--canvas-fill': '#ffffff',
        '--canvas-stroke': '#bababa',
        '--node': '#42b983',
        '--stroke': '#6b6b6b',
        '--fill': '#eaeaeb',
        '--hover-and-sel': '#ffe99b',
        '--wire-draw': '#6b6b6b',
        '--wire-cnt': '#42b983',
        '--wire-pow': '#52e539',
        '--wire-sel': '#0fb2f2',
        '--wire-lose': '#f10530',
        '--mini-map': '#42b983',
        '--mini-map-stroke': '#0fb2f2',
        '--input-text': '#42b983',
        '--output-rect': '#0487d9',
        '--secondary-stroke': '#f10530',
        '--text': '#454545',
        '--wire-norm': '#006839',
        '--node-norm': '#ffc231',
        '--splitter': '#00b462',
        '--disable': '#656565',
        '--table-head-dark': '#ffffff',
    },
    'G&W': {
        '--text-navbar--alt': '#000000',
        '--br-secondary': '#6b6b6b',
        '--cus-radio_label': '#6b6b6b',
        '--primary': '#eaeaeb',
        '--text-dark': '#6b6b6b',
        '--text-lite': '#ffffff',
        '--text-panel': '#656565',
        '--bg-navbar': '#6b6b6b',
        '--qp-br-tl': '#969696',
        '--qp-br-rd': '#545454',
        '--qp-box-shadow-1': '#747474',
        '--qp-box-shadow-2': '#5f5f5f',
        '--bg-tabs': '#a4a4a4',
        '--br-circuit-cur': '#6b6b6b',
        '--bg-circuit': '#d7d7d7',
        '--br-circuit': '#6b6b6b',
        '--br-primary': '#6b6b6b',
        '--context-text-hov': '#6b6b6b',
        '--context-text': '#ffffff',
        '--bg-primary-moz': 'rgba(107, 107, 107, 0.904)',
        '--bg-primary-chr': 'rgba(107, 107, 107, 0.704)',
        '--bg-icons': '#dddddd',
        '--bg-text': '#dddddd',
        '--bg-secondary': '#6b6b6b',
        '--bg-toggle-btn-primary': '#3ac8a4',
        '--primary-btn-hov': '#71d7bd',
        '--btn-danger': '#fc8771',
        '--btn-danger-darken': '#fdb2a4',
        '--cus-btn-hov--bg': '#3ac8a4',
        '--cus-btn-hov-text': '#ffffff',
        '--canvas-fill': '#ffffff',
        '--canvas-stroke': '#bababa',
        '--node': '#42b983',
        '--stroke': '#6b6b6b',
        '--fill': '#eaeaeb',
        '--hover-and-sel': '#ffe99b',
        '--wire-draw': '#6b6b6b',
        '--wire-cnt': '#42b983',
        '--wire-pow': '#52e539',
        '--wire-sel': '#0fb2f2',
        '--wire-lose': '#f10530',
        '--mini-map': '#42b983',
        '--mini-map-stroke': '#0fb2f2',
        '--input-text': '#42b983',
        '--output-rect': '#0487d9',
        '--secondary-stroke': '#f10530',
        '--text': '#454545',
        '--wire-norm': '#006839',
        '--node-norm': '#ffc231',
        '--splitter': '#00b462',
        '--disable': '#656565',
        '--table-head-dark': '#ffffff',
    },
    'High Contrast': {
        '--text-navbar--alt': '#000000',
        '--br-secondary': '#f38518',
        '--cus-radio_label': '#000000',
        '--primary': '#000000',
        '--text-dark': '#000000',
        '--text-lite': '#ffffff',
        '--text-panel': '#ffffff',
        '--bg-navbar': '#000000',
        '--qp-br-tl': '#f38518',
        '--qp-br-rd': '#f38518',
        '--qp-box-shadow-1': '#0d0d0d',
        '--qp-box-shadow-2': '#0d0d0d',
        '--bg-tabs': '#616161',
        '--text-circuit': '#000000',
        '--br-circuit-cur': '#f38518',
        '--bg-circuit': '#b6b6b6',
        '--br-circuit': '#f38518',
        '--br-primary': '#f38518',
        '--context-text-hov': '#000000',
        '--context-text': '#ffffff',
        '--bg-primary-moz': 'rgba(0, 0, 0, 0.904)',
        '--bg-primary-chr': 'rgba(0, 0, 0, 0.704)',
        '--bg-icons': '#262626',
        '--bg-text': '#dddddd',
        '--bg-secondary': '#6b6b6b',
        '--bg-toggle-btn-primary': '#009599',
        '--primary-btn-hov': '#00b1b6',
        '--btn-danger': '#e45605',
        '--btn-danger-darken': '#fa792f',
        '--cus-btn-hov--bg': '#009599',
        '--cus-btn-hov-text': '#ffffff',
        '--canvas-fill': '#000000',
        '--canvas-stroke': '#9ad5e9',
        '--node': '#26a841',
        '--stroke': '#626262',
        '--fill': '#d4d4d4',
        '--hover-and-sel': '#ffdf6c',
        '--wire-draw': '#909090',
        '--wire-cnt': '#3bb15b',
        '--wire-pow': '#3ac53c',
        '--wire-sel': '#049ffb',
        '--wire-lose': '#f42f0b',
        '--mini-map': '#1c2427',
        '--mini-map-stroke': '#000000',
        '--input-text': '#42b983',
        '--output-rect': '#005682',
        '--secondary-stroke': '#f7081e',
        '--text': '#ffffff',
        '--wire-norm': '#00b965',
        '--node-norm': '#f38518',
        '--splitter': '#21de5a',
        '--disable': '#262626',
        '--table-head-dark': '#000000',
    },
    'Color Blind': {
        '--text-navbar--alt': '#000000',
        '--br-secondary': '#e2dad1',
        '--cus-radio_label': '#2e2b21',
        '--primary': '#2e2b21',
        '--text-dark': '#000000',
        '--text-lite': '#ffffff',
        '--text-panel': '#ffffff',
        '--bg-navbar': '#2e2b21',
        '--qp-br-tl': '#716950',
        '--qp-br-rd': '#6c654d',
        '--qp-box-shadow-1': '#4f4a38',
        '--qp-box-shadow-2': '#302d23',
        '--bg-tabs': '#9a9a9a',
        '--text-circuit': '#000000',
        '--br-circuit-cur': '#e2dad1',
        '--bg-circuit': '#d6d6d6',
        '--br-circuit': '#e2dad1',
        '--br-primary': '#e2dad1',
        '--context-text-hov': '#000000',
        '--context-text': '#ffffff',
        '--bg-primary-moz': 'rgba(46, 43, 33, 1)',
        '--bg-primary-chr': 'rgba(46, 43, 33, 1)',
        '--bg-icons': '#9c7762',
        '--bg-text': '#dddddd',
        '--bg-secondary': '#6b6b6b',
        '--bg-toggle-btn-primary': '#bfaac1',
        '--primary-btn-hov': '#ccbbcd',
        '--btn-danger': '#b66e43',
        '--btn-danger-darken': '#ba7144',
        '--cus-btn-hov--bg': '#b66e43',
        '--cus-btn-hov-text': '#ffffff',
        '--canvas-fill': '#ffffff',
        '--canvas-stroke': '#8d88ad',
        '--node': '#c59434',
        '--stroke': '#342a1f',
        '--fill': '#e0dcd3',
        '--hover-and-sel': '#f4d4d4',
        '--wire-draw': '#4c4c4c',
        '--wire-cnt': '#908eb9',
        '--wire-pow': '#b3b1cf',
        '--wire-sel': '#a7b8f8',
        '--wire-lose': '#f42f0b',
        '--mini-map': '#4b4636',
        '--mini-map-stroke': '#000000',
        '--input-text': '#756d54',
        '--output-rect': '#092c48',
        '--secondary-stroke': '#cdb1ad',
        '--text': '#000000',
        '--wire-norm': '#7f7cae',
        '--node-norm': '#c59434',
        '--splitter': '#836222',
        '--disable': '#956c6a',
        '--table-head-dark': '#2e2b21',
    },
}

const CUSTOM_THEME_KEY = 'Custom Theme';

const CSS_COLOR_REGEX = /^#[0-9a-fA-F]{6}$/;

function loadStoredCustomTheme(): Record<string, string> {
    try {
        if (typeof window === 'undefined' || !window.localStorage) {
            return {};
        }
        const raw = window.localStorage.getItem(CUSTOM_THEME_KEY);
        if (!raw) {
            return {};
        }
        const parsed = JSON.parse(raw);
        if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
            const validated: Record<string, string> = {};
            for (const [key, value] of Object.entries(parsed)) {
                if (typeof value === 'string' && CSS_COLOR_REGEX.test(value)) {
                    validated[key] = value;
                }
            }
            return validated;
        }
        return {};
    } catch {
        return {};
    }
}

Object.defineProperty(themes, CUSTOM_THEME_KEY, {
    get() {
        const storedCustomTheme = loadStoredCustomTheme();
        return {
            ...themes['Default Theme'],
            ...storedCustomTheme,
        };
    },
    enumerable: true,
});

export default themes;