import { EventQueue } from "../eventQueue";
import type { CircuitElement } from "../types/circuitElement.types";
export interface SimulationArea {
  canvas: HTMLCanvasElement;
  context: CanvasRenderingContext2D | null;
  selected: boolean;
  hover: boolean | undefined | Record<string, any>;
  clockState: number;
  clockEnabled: boolean;
  lastSelected: CircuitElement | null | undefined;
  stack: CircuitElement[];
  prevScale: number;
  oldx: number;
  oldy: number;
  objectList: CircuitElement[];
  maxHeight: number;
  maxWidth: number;
  minHeight: number;
  minWidth: number;
  multipleObjectSelections: CircuitElement[];
  copyList: CircuitElement[];
  shiftDown: boolean;
  controlDown: boolean;
  timePeriod: number;
  mouseX: number;
  mouseY: number;
  mouseDownX: number;
  mouseDownY: number;
  simulationQueue: EventQueue;
  clickCount: number;
  lock: string;
  mouseDown: boolean;
  ClockInterval: NodeJS.Timeout | null;
  touch: boolean;
  timer: () => void;
  setup: () => void;
  changeClockTime: (t: number) => void;
  clear: () => void;
}
