name: CI and CD

on:
  push:
    branches:
      - master
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm install
      - run: npm run build
      - run: npm test
      - name: Deploy
        uses: crazymax/ghaction-github-pages@v1
        with:
          target-branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_REPO_TOKEN}}