name: Conventional Commits

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-commits:
    permissions:
      contents: read
      pull-requests: read
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webiny/action-conventional-commits@v1.3.0
