name: Update Changelog

on:
  push:
    branches: [main]

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install -g semantic-release
          npm install @semantic-release/changelog @semantic-release/git

      - name: Configure semantic-release
        run: |
          echo 'module.exports = {
            branches: ["main"],
            plugins: [
              ["@semantic-release/commit-analyzer", {
                "preset": "conventionalcommits",
                "releaseRules": [
                  {"type": "*", "release": false} # Never auto-release
                ]
              }],
              "@semantic-release/changelog",
              ["@semantic-release/git", {
                "assets": ["CHANGELOG.md"],
                "message": "docs(changelog): Update for unreleased changes [skip ci]"
              }]
            ]
          }' > release.config.js

      - name: Update CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release --dry-run --no-ci --extends ./release.config.js